#!/usr/bin/env bash

# basic config
environment=production  # should be one of (development, staging, production)
branch=master  # what branch to deploy

function setup {
    composer update --no-interaction || exit 1
    npm prune || exit 2
    npm install || exit 3
}

# further customization; usually there's no need to change any of this
homedir=~/$environment  # overwrite if using non-default install location


# update code and perms
cd $homedir/app
git fetch origin || exit 100
git reset --hard origin/$branch || exit 101
setup
chgrp -Rf www-data . || exit 102
cd ..
